### ISSUE TITLE
dcos cli for apache mesos

### ISSUE THREAD

**Issue by jianzzz** [dcos/dcos-cli#1055]
Hi, we are using apache mesos now in the production environment，but it's mesos-cli has been deprecated. It's there any way to use dcos-cli for apache mesos? We need to attach docker container.

**Comment by ArmandGrillet** [comment]
Apache Mesos has a _new_ CLI now: https://github.com/apache/mesos/tree/master/src/python/cli_new For more information: https://www.youtube.com/watch?v=3NQ0wu0CoxU&t=2s
