### ISSUE TITLE
https://dcos.io/docs/latest/usage/cli/ seems to be broken

### ISSUE THREAD

**Issue by jeschkies** [dcos/dcos-cli#1064]
https://dcos.io/docs/latest/usage/cli/ redirects me to a "Ooops" message.

**Comment by bamarni** [comment]
@klueska : I don't have permission to edit the link, I think it should be https://dcos.io/docs/latest/cli/ (please not the `latest` and not `1.10`, as you're automatically redirected when clicking).

**Comment by bamarni** [comment]
Thanks for notifying, fixed now.
