### ISSUE TITLE
CLI compatibility matrix?

### ISSUE THREAD

**Issue by oliverlockwood** [dcos/dcos-cli#1077]
In the [DC/OS v1.7 docs](https://dcos.io/docs/1.7/usage/cli/install/) it says that:
>1.8 CLI is compatible with DC/OS 1.6.1 forward

Apart from that statement, I can't find anywhere that documents the compatibility between different versions of the CLI (we now have 1.9 and 1.10) with various versions of a DC/OS cluster.  Is this information available somewhere?

I'm hoping that you'll tell me something like "an uplevel version of CLI supports all older cluster versions, but newly introduced CLI functionality may not work against an older cluster".  But whether or not the answer is that, some sort of statement would be helpful 😃

**Comment by bamarni** [comment]
We are trying to preserve backwards compatibility as much as we can. The recommended way to install the CLI is to click on the link on the top left of the DCOS/UI, this makes sure you get the correct version for your cluster.

However with the introduction of the new cluster subcommand, we are considering ways to support your use-case (dealing with different cluster versions with the came CLI). This might involve making the CLI only containing the cluster subcommand by default and downloading the correct binary version in the cluster dir, where it'll proxy calls for other subcommands. But this is still being discussed internally.

**Comment by klueska** [comment]
At present, the only supported CLI for a given cluster is the one
downloadable from its GUI. This is obviously not ideal, and we are working
on a way to make this experience better in the near future.

Kevin

**Comment by oliverlockwood** [comment]
Thanks @klueska and @bamarni both for answering so promptly.  I conclude from your answers that, as things stand: _**an uplevel CLI might still work, if I'm lucky, but that's not formally supported.**_

@bamarni, if and when there's a Github issue that I can track for those proposals you're talking about, please would you direct me to it so I can be kept aware?

For the interest of anyone else who stumbles upon this, if we hit issues with back-compatibility, then in order to achieve programmatic continuous delivery to multiple DC/OS clusters, we may have to build and maintain something which runs along the lines of:
1.  hitting the `dcos-version` endpoint on the cluster (`http://<cluster-ip>/dcos-metadata/dcos-version.json?_timestamp=1507886377214`) to retrieve cluster information, e.g.:
    ```json
    {
        "version": "1.9.2",
        "dcos-image-commit": "9928208d6d00f0721bffd548642445d396aaab01",
        "bootstrap-id": "79a0dfe0944948a33ab75f6e62335f166e117f3d"
    }
    ```
2.  Templating the `major.minor` part of the version string into the GUI-provided CLI download instructions.

**Comment by bamarni** [comment]
We use JIRA as ticketing system, I've created this one : https://jira.mesosphere.com/browse/DCOS_OSS-1756

We'll link there a design doc proposal in the next weeks. There is also an early draft [here](https://github.com/bamarni/dcos_cli/tree/dev), mainly about the base package structure.

**Comment by luisdavim** [comment]
I see that you're using the click library, that's great, we've started using that ourselves for an internal CLI tool and it's great, we're following some of the patterns described here https://gist.github.com/beddari/398600a2a59f6066fc858b57524a6c29

**Comment by ArmandGrillet** [comment]
We have added a warning when there is a compatibility problem between the CLI and the cluster (this warning has been backported to all our supported CLIs) to make things clearer.
