### ISSUE TITLE
homebrew-ed dcos-cli reports "SNAPSHOT" as version

### ISSUE THREAD

**Issue by oschrenk** [dcos/dcos-cli#1083]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

Well, I guess herein lies the crux of the matter. I'm guessing I'm using 0.5.5, but who knows.

### What operating system and version are you using?

macOS 10.13.1 Beta (17B35a)

### What did you do?
If possible please provide a recipe for reproducing.

```
$ brew install dcos-cli
$ dcos --version
dcoscli.version=SNAPSHOT
dcos.version=N/A
dcos.commit=N/A
dcos.bootstrap-id=N/A
```

### What did you expect to see?

```
dcoscli.version=0.5.5
```

### What did you see instead?

```
$ dcos --version
dcoscli.version=SNAPSHOT
dcos.version=N/A
dcos.commit=N/A
dcos.bootstrap-id=N/A
```

**Comment by bamarni** [comment]
At the moment the only supported way to install the CLI is by following instructions on the DC/OS UI (clicking on the top-left corner, then "Install CLI" would give you instructions on how to do it). Downloading from the appropriate URL depending on the cluster version (eg. https://downloads.dcos.io/binaries/cli/linux/x86-64/dcos-1.10/dcos). This makes sure you have the proper version for your cluster.

The homebrew package seems to be maintained by community members : https://github.com/Homebrew/homebrew-core/pull/13378 and they might release it differently than we do and omit the version information (cc @msabramo).

That being said, now that the cluster subcommand has been introduced we are in the process of refactoring the CLI to make it handle multiple clusters of potentially different versions without backward or forward compatibility issues (https://jira.mesosphere.com/browse/DCOS_OSS-1756).
