### ISSUE TITLE
Install package timeout

### ISSUE THREAD

**Issue by whisper-bye** [dcos/dcos-cli#1129]
dcoscli.version=0.5.7
dcos.version=1.10.2
Centos 7

```
# macOS
> dcos package install tunnel-cli --cli
Request to URL [http://192.168.0.123/package/describe] timed out.
```

192.168.0.123 is my master node

**Comment by adamtheturtle** [comment]
Thank you @whisper-bye for the report. I'm hoping that https://github.com/dcos/dcos-cli/pull/1126 has fixed this issue and that it will be available in the next release.

cc @bamarni

**Comment by whisper-bye** [comment]
is great, thx!
