### ISSUE TITLE
How to redeploy/update Marathon applications/services stack  already running in a DC/OS cluster, with new definition file (.json) 

### ISSUE THREAD

**Issue by sandeep000** [dcos/dcos-cli#1177]
I am new to Marathon and DC/OS

We have a stack of applications already running in the DC/OS, now I want to redeploy these applications with new JSON file, can you please guide me how this can be done??
We are using the latest version of DC/OS and DC/OS CLI

**Comment by ArmandGrillet** [comment]
I suggest you to read this page in our documentation: https://docs.mesosphere.com/1.12/cli/command-reference/dcos-marathon/dcos-marathon-app-update/
If you have other questions related to DC/OS, please join our community on Slack: https://chat.dcos.io/
