### ISSUE TITLE
Spark properties spark.mesos.driverEnv.[EnvironmentVariableName] does not work via the DCOS cli

### ISSUE THREAD

**Issue by dromard** [dcos/dcos-cli#1199]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
dcoscli.version=0.5.7
dcos.version=1.10.0

### What operating system and version are you using?
Ubuntu 16.04.3 LTS (GNU/Linux 4.11.0-1015-azure x86_64)

### What did you do?
I launch spark with the dcos cli using the following command 

**dcos spark --name="sparkdispatcher" run  --submit-args="--executor-memory 5G --driver-memory 5G \
--conf spark.cores.max=4 \
--conf spark.executor.cores=2 \
--class com.geosys.agriquest.weather.reader.SparkReaderDCOS \
--conf spark.mesos.executor.docker.image=cnero/spark:1.1.0-2.1.1-hadoop-2.7 \
--conf 'spark.mesos.driverEnv.PROCESSOR_SPARK_LEVELPARA=3' \ 
http://X.31.1.107:8081/artifactory/libs-snapshot-local/com/geosys/coretech/agriquest/agriquest-weather-spark-reader_2.11/0.1-SNAPSHOT/agriquest-weather-spark-reader_2.11-0.1-SNAPSHOT.jar http://X.31.1.107:8081/artifactory/libs-snapshot-local/com/geosys/coretech/agriquest/agriquest-weather-spark-reader_2.11/0.1-SNAPSHOT/agriquest-weather-spark-reader_2.11-0.1-SNAPSHOT.properties"

The application fails, whereas it is not the case when I simply do the following command

dcos spark --name="sparkdispatcher" run  --submit-args="--executor-memory 5G --driver-memory 5G \
--conf spark.cores.max=4 \
--conf spark.executor.cores=2 \
--class com.geosys.agriquest.weather.reader.SparkReaderDCOS \
--conf spark.mesos.executor.docker.image=cnero/spark:1.1.0-2.1.1-hadoop-2.7 \
http://X.31.1.107:8081/artifactory/libs-snapshot-local/com/geosys/coretech/agriquest/agriquest-weather-spark-reader_2.11/0.1-SNAPSHOT/agriquest-weather-spark-reader_2.11-0.1-SNAPSHOT.jar http://X.31.1.107:8081/artifactory/libs-snapshot-local/com/geosys/coretech/agriquest/agriquest-weather-spark-reader_2.11/0.1-SNAPSHOT/agriquest-weather-spark-reader_2.11-0.1-SNAPSHOT.properties"

### What did you expect to see?

I should be able to get the env variable .PROCESSOR_SPARK_LEVELPARA=3 in the driver container.

### What did you see instead?

Instead I got the following warning in the stderr of the driver
 WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/bin/sh: 1: --conf: not found
I0403 10:16:48.319874 26726 process.cpp:1072] Failed to accept socket: future discarded

**Comment by dromard** [comment]
I found the solution. In fact in one of my env variable I used a '&' and it seems that we cannot use it in an env variable. 

So  I changed the env variable so that it does not use any longer the & sign. Furthermore,  I did not find any way to protect this special character.

So the spark.mesos.driverEnv.[EnvironmentVariableName] property works fine till we do not use env variable containing  &.

**Comment by ArmandGrillet** [comment]
Thanks for the update. The subcommand `spark` is not part of the DC/OS CLI, you can find the code here: https://github.com/mesosphere/spark-build/tree/master/cli
