### ISSUE TITLE
download log bundle without prompt

### ISSUE THREAD

**Issue by zencircle** [dcos/dcos-cli#1438]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
dcos --version
dcoscli.version=0.6.1
dcos.version=1.11.6
dcos.commit=e23128e161c6c7892b204b1da43e5f27cd64a208
dcos.bootstrap-id=77363b95b2e10437598ae4d27771b14158a5923d

### What operating system and version are you using?
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Wed Jun 27 04:30:39 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
### What did you do?
dcos node diagnostics download $(dcos node diagnostics --list | grep -v Available | awk '{print $1}' | tail -n1)
Diagnostics bundle size is 250.0MiB, are you sure you want to download it? [yes/no] yes
Diagnostics bundle downloaded to /root/bundle-2019-02-01-1549035618.zip

If possible please provide a recipe for reproducing.

### What did you see instead?
dcos node diagnostics download --yes  bundle-2019-02-01-1549035618.zip
(--yes or -y) which would allow to download bundle without prompt

**Comment by janisz** [comment]
This option is deprecated. Please use `dcos diagnostics download`

**Comment by zencircle** [comment]
why is this issue closed without fix, there is no option available to download without prompt https://docs.d2iq.com/mesosphere/dcos/2.1/cli/command-reference/dcos-diagnostics/dcos-diagnostics-download/
