### ISSUE TITLE
Cannot use regular expression in task command

### ISSUE THREAD

**Issue by TPapajCin** [dcos/dcos-cli#1454]
### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
dcoscli.version=0.5.7
dcos.version=1.11.0
dcos.commit=b6d6ad4722600877fde2860122f870031d109da3
dcos.bootstrap-id=a0654657903fb68dff60f6e522a7f241c1bfbf0f

### What operating system and version are you using?
Ubuntu 16.04 LTS

### What did you do?
I am trying to exec into /bin/bash of container running Spark executor to debug problems. My **task exec** shows Spark executors with IDs like **0** or **1** etc. I am using command like `dcos task exec --tty --interactive "0" /bin/bash`

Of course using **0** as **<task>** argument ends with error because it's interpreted always as a **partial ID** and there are lot of 0s in task IDs.
Task command says that **<task>** argument can be `A full task ID, a partial task ID, or a regular expression.` So I tried to use regular expression but it does not work possibly because I am not doing this right, however documentation does not give any examples. The command also does not contain **--regex** option to force command to parse argument as a regular expression. I tried things like **^0$** or **/0/** but **dcos task** commands always interprets it literally and always as a substring. So I cannot force **dcos task** command to interpret **<path>** as a full task ID or regular expression. It seems that my case is very specific one because I could not find any examples of this on the internet.

### What did you expect to see?
Successful access into task container.

### What did you see instead?
`There are multiple tasks with ID matching [0]`

### More informations
Documentation is unfortunately useless for this because https://docs.mesosphere.com/1.11/cli/command-reference/dcos-task/dcos-task-exec/ refers to https://docs.mesosphere.com/1.11/monitoring/debugging/task-exec/ and that page refers to https://docs.mesosphere.com/1.11/cli/command-reference/dcos-task/dcos-task-exec/ . 1.12 version of the documentation has the same problem.

**Comment by bamarni** [comment]
Hi @TPapajCin , sorry for the delay, the help documentation is misleading here as it accepts wildcards only and not a regex, see https://github.com/dcos/dcos-core-cli/commit/2ffb2468d85a25bf0cefa609622c898f5163dda5#diff-50e236080de379adda367353aabc19a5.

I'll follow-up with a documentation PR.
