### ISSUE TITLE
dcos-cli not working if cluster installed with oauth_enabled: false

### ISSUE THREAD

**Issue by julienlau** [dcos/dcos-cli#1484]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

Tested with 1.11 and 1.13

[root@mesos-bootstrap]> dcos --version
dcoscli.version=0.6.6
dcos.version=1.11.3
dcos.commit=96f364a598e5f06371794ebb7c40fff65d0c289f
dcos.bootstrap-id=6a177efb1f3c1358110fc434910b5310f504c169
[root@mesos-bootstrap]> dcos auth login
Login successful!
[root@mesos-bootstrap]> dcos task log spark.2853082b-9e60-11e9-ada7-9ad74aef92bf
Authentication failed. Please run `dcos auth login`.
 
----------

[centos@dcos-bootstrap.novalocal]> dcos --version
dcoscli.version=fbd767d6f55c15c2f9dcf7d1ba56734fdd79963d
dcos.version=1.13.1
dcos.variant=open
dcos.commit=f59e02457b5cd64ef14f94f79eb92db15b2d91f6
dcos.bootstrap-id=34c4df28151beb435a1c1cb9c80924f952b17e04
[centos@dcos-bootstrap.novalocal]> dcos task log spark-history.instance-c707ce54-91e0-11e9-a737-6a9dd2b4457c._app.3
Your core.dcos_acs_token is invalid. Please run: `dcos auth login`
[centos@dcos-bootstrap.novalocal]> dcos auth login
Error: authentication disabled

### What operating system and version are you using?
CentOS 7.5

### What did you do?
See above "dcos task log" needs a login. dcos auth login is succesful but does not make things work.

### What did you expect to see?

Log of a DCOS task.

### What did you see instead?

Error message.

Please be aware that it does not only affect "dcos task" command. Other command are also failing.

**Comment by mimmus** [comment]
Same for me

**Comment by makkes** [comment]
Hi @julienlau @mimmus, sorry for the huge delay in responding to your issue. `oauth_enabled: false` is not a very well supported configuration so this is pretty low on our priority list. You're very welcome to open a PR for this, though.

**Comment by mimmus** [comment]
oauth_enables:false is a supported DC/OS config
Fortunately there is a simple workaround (setting a dummy token).

**Comment by Phobos-7** [comment]
> oauth_enables:false is a supported DC/OS config Fortunately there is a simple workaround (setting a dummy token).

Our oath stopped working, we need to migrate but can't log in to it. How can we disable oath in our cluster? Thanks!

**Comment by siddana123** [comment]
How to disable oath in the DCOS cluster,

**Comment by siddana123** [comment]
We are having gmail users for login into the DCOS web login, Suddenly all gmail users not able to login into the DCOS cluster.
