### ISSUE TITLE
Dcos-cli can't update jobs or create jobs with force-pull or privileges set to True

### ISSUE THREAD

**Issue by karlohrn** [dcos/dcos-cli#1494]
What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
dcoscli.version=fbd767d6f55c15c2f9dcf7d1ba56734fdd79963d
dcos.version=1.13.3
dcos.variant=open
dcos.commit=450f27d17908e25c54a5ac4d861d522d6363e85c
dcos.bootstrap-id=258e1f02d00700ee1ba03cf500d050476b44e28c

Centos 7.6

So i was trying to create a job with dcos-cli that both needed privileges set to True and force-pull set to True. 

Dcos job add job.json

job.json:
```
{
  "id": "job",
  "description": "run",
  "run": {
    "cpus": 1,
    "mem": 1024,
    "disk": 0,
    "cmd": "sleep 20",
    "env": {},
    "placement": {
      "constraints": []
    },
    "artifacts": [],
    "maxLaunchDelay": 3600,
    "volumes": [],
    "restart": {
      "policy": "NEVER"
    },
    "secrets": {},
    "docker": {
      "image": "myimage",
      "privileged": true,
      "forcePullImage": true
    }
  },
  "schedules": []
}
```

But DCOS dose not read the privileged or force-pull tag and instead set them to the default value of false.

same happens if i try to use the "dcos job update job.json" it will just ignore the setting or if the settings where set to true in another way override them with false.

If possible please provide a recipe for reproducing.
1, create a job with forcepull set to true
2, dcos job show "created job"
3, update the settings of a already existing job and try to set them to true
4, look to see if they are set and see that both are reverted back to false even if they where set to true previously.

**Comment by bamarni** [comment]
Hi @karlohrn

Thanks for the report, we fixed `forcePullImage` in https://github.com/dcos/dcos-core-cli/commit/de3f9cbabcad82d2b29695137a7739162a6684c2

I'll be working on syncing our Go type with the schema in https://github.com/dcos/metronome/blob/master/api/src/main/resources/public/api/v1/schema/jobspec.schema.json
