### ISSUE TITLE
dcos-marathon should support --service=marathon-user

### ISSUE THREAD

**Issue by sttts** [dcos/dcos-cli#396]
Right now it is only possible to use one marathon framework instance with the marathon cli command. Compare https://github.com/mesosphere/dcos-cli/blob/master/dcos/marathon.py#L31.

As users might install multiple marathons, the cli should support this, i.e. switching via the command line.

**Comment by aquamatthias** [comment]
+1

**Comment by sttts** [comment]
Setting marathon.url in the dcos config works at least. But a user will never find out without reading the code.

```
[marathon]
url = "http://pool-c73d-elasticl-13c45jhfzyebl-1471334914.us-west-2.elb.amazonaws.com/service/marathon-user/"
```

**Comment by ssk2** [comment]
+1

**Comment by jsancio** [comment]
Adding both the `marathon` and `core` label since we may want to resolve it in a general so that all command that may use this feature.
