### ISSUE TITLE
deprecate --app-id flag for `package install`

### ISSUE THREAD

**Issue by tamarrow** [dcos/dcos-cli#463]

**Comment by ssk2** [comment]
The `--app-id` option overwrites the Marathon application ID when installing a package. This generally does a poor job of installing packages.

Typically packages will use the framework-name property throughout their configuration. This is used for namespacing Marathon applications (i.e. jenkins-1, jenkins-2) as well as namespacing paths to persistent storage - e.g. when using ZooKeeper or a filesystem (i.e. /tmp/jenkins/jenkins-1, /tmp/jenkins/jenkins-2). 

This property is also used by the DCOS UI to display it in the list of running services. When using `--app-id`, the framework-name is often left to the default (assuming the user doesn't also use the --options flag). This means that the DCOS UI shows multiple applications of the same name

**Comment by surdy** [comment]
From the perspective of a user I can see them being confused/bitten by this because is might end up doing something the did not expect.

**Comment by surdy** [comment]
Are there any know things that might break if we remove `--app-id` today ? I would like see `--app-id` go away sooner rather than later ( for lesser confusion for customers)

**Comment by ssk2** [comment]
Nope! Can you submit a PR @surdy? :)

**Comment by ArmandGrillet** [comment]
This is not present in recent versions of the CLI:
```
    dcos package install <package-name>
                         [(--cli [--global]) | --app]
                         [--package-version=<package-version>]
                         [--options=<file>]
                         [--yes]
```
