### ISSUE TITLE
'dcos package install': display version number before confirmation?

### ISSUE THREAD

**Issue by nickbp** [dcos/dcos-cli#544]
$ dcos package install kafka
This will install Apache Kafka DCOS Service.
Continue installing? [yes/no] yes
Installing Marathon app for package [kafka] version [0.9.0.1-0.2.4]
Installing CLI subcommand for package [kafka] version [0.9.0.1-0.2.4]

Ideally the '0.9.0.1-0.2.4' could be displayed sometime before I confirm the installation. Some possible alternatives:
- "Continue installing version [0.9.0.1-0.2.4]? [yes/no]"
-  "This will install Apache Kafka DCOS Service (version 0.9.0.1-0.2.4)"

This mainly comes up in cases where I'm pointing to an experimental version of the package in my repo list. I often forget "--index=0" when adding an experimental repo and end up accidentally installing an old version of the package.

**Comment by tamarrow** [comment]
`This will install Apache Kafka DCOS Service.` is the `preInstallNotes`: https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/K/kafka/6/package.json#L15.  Not much we can do there since we have no control over what that string contains.
