### ISSUE TITLE
Mechanism for getting the version of DC/OS

### ISSUE THREAD

**Issue by jsancio** [dcos/dcos-cli#567]
Please answer the following questions before submitting your issue. Thanks!

### What version of the DCOS CLI are you using (`dcos --version`)?
SNAPSHOT

### What version of DCOS are you using?
1.6.1

### What operating system and version are you using?
Fedora 22

### What did you do?
If possible please provide a recipe for reproducing.
I am trying to get the version of DC/OS

### What did you expect to see?
`dcos --version` should display the CLI version and the DC/OS version. I don't know if this is the right solution but the user should be able to get the version of DC/OS. This helps to debug issues.

### What did you see instead?
`dcos --version` only shows the version of the CLI

**Comment by tamarrow** [comment]
We could output {DCOS_VERSION: 1-7.dev, DCOS_CLI_VERSION: 0.4.2}.
We can get the dcos_version from `dcos-metadata/dcos-version.json`

**Comment by jsancio** [comment]
Sounds good to me.
