### ISSUE TITLE
DCOS package describe with options file not collated

### ISSUE THREAD

**Issue by ksivask** [dcos/dcos-cli#576]
### What version of the DCOS CLI are you using (`dcos --version`)?
dcos version 0.4.2

### What version of DCOS are you using?
DCOS 1.7

### What operating system and version are you using?
Centos 7.2

### What did you do?
dcos --debug  package describe --config --options=/tmp/test-config.json test-package

### What did you expect to see?
the package's config.json merged with the options' test-config.json

### What did you see instead?
only saw the original package's config.json. the options argument was not merged.

**Comment by tamarrow** [comment]
You can get that by using `--render` instead of `--config`.
`dcos package --help` has the full documentation of package commands and config params.

**Comment by ksivask** [comment]
tried everything:
a) dcos package describe --render --options=/tmp/test-config.json test-package
the output is the same as the "dcos package describe test-package"

b) dcos package describe --config --render --options=/tmp/test-config.json test-package
the output is the same as the "dcos package describe --config test-package"

**Comment by tamarrow** [comment]
Ah, you need: `--app`: `dcos package describe --app --render --option=/tmp/test-config.json test-package`

**Comment by jsancio** [comment]
Yeah. This is a very difficult to discover feature. We should consider adding a top level command like `dcos package render`

**Comment by tamarrow** [comment]
I think we should change the functionality. `--config` should print the config with options, if they are given. and if you have --render or --options we should require --app, --config or --cli

**Comment by tamarrow** [comment]
^my above comment is done, so closing this issue.
