### ISSUE TITLE
provide endpoints for service and admin interface upon successful package installation

### ISSUE THREAD

**Issue by fernandosanchezmunoz** [dcos/dcos-cli#585]
As a way to simplify the package installation/usage workflow, it would be very useful to finish the installation process by providing endpoints for accessing the service itself (and the admin interface where applicable) to the end user. This way, end users wouldn't have to navigate inside DCOS or Marathon to look for port numbers or IP addresses of the nodes where executors are running.

Currently the output provided is:

```
$ dcos package install chronos
We recommend a minimum of one node with at least 1 CPU and 2GB of RAM available for the Chronos Service.
Continue installing? [yes/no] yes
Installing Marathon app for package [chronos] version [2.4.0]
Chronos DCOS Service has been successfully installed!

	Documentation: http://mesos.github.io/chronos
	Issues: https://github.com/mesos/chronos/issues
```
This request is to add to this output information along the lines of:

```
Chronos DCOS Service is listening for requests at http://node_x_address:8080
Chronos DCOS Admin interface is available at http://master_node/service/chronos

```

**Comment by tamarrow** [comment]
Right now if the package maintainer adds a `postInstallNotes` field to their package definition, those will be printed after installation.

**Comment by tamarrow** [comment]
@fernandosanchezmunoz anything more than `postInstallNotes` you'd like to see?

**Comment by tamarrow** [comment]
Talked with @fernandosanchezmunoz, closing.
