### ISSUE TITLE
Provide non-interactive login to make dcos-cli scripting friendly

### ISSUE THREAD

**Issue by lloesche** [dcos/dcos-cli#588]
Right now `dcos auth login` is interactive. This means whenever the auth token expires a user has to manually login. This prohibits the use of dcos-cli in any kind of batch jobs or automated scripts.

It would be nice if the login credentials could be provided als CLI args.

At the moment a user as to come up with workarounds like implementing his own token fetcher that updates ~/.dcos/dcos.toml or write an expect script like the following:
```
#!/usr/bin/env expect -f
set timeout 10
set login [lrange $argv 0 0]
set password [lrange $argv 1 1]
spawn dcos auth login
expect "username: "
send "$login\n"
expect "password: "
send "$password\n"
expect eof
```

**Comment by jsancio** [comment]
cc @alberts @pyronicide 

@lloesche I haven't tried this but you should be able to encode the username and password in the URL for Enterprise builds. E.g. `dcos config set core.dcos_url https://user:pass@dcoshost`

**Comment by lloesche** [comment]
@jsancio Tamar just helped me out. For DC/OS EE I can specify user:pass as part of the core.dcos_url and for DC/OS I can `echo auth-token | dcos auth login`. That solves it!
