### ISSUE TITLE
Add optional command parameter to docs node ssh

### ISSUE THREAD

**Issue by surdy** [dcos/dcos-cli#609]
It would be awesome to be able to specify an optional argument to `dcos node ssh` to run a command over ssh and exit instead of ssh-ing into the node. Similar to how ssh does it.

e.g. `dcos node ssh --mesos-id<id> "curl -s ifconfig.co"` can be used to get public IP of the node

As a workaround commands can be piped into dcos node ssh to get similar behaviour. But I would prefer a cleaner command.

Please answer the following questions before submitting your issue. Thanks!

### What version of the DCOS CLI are you using (`dcos --version`)?
4.4.0

### What version of DCOS are you using?
1.7

### What operating system and version are you using?
CentOS

### What did you do?
If possible please provide a recipe for reproducing.
dcos node ssh --mesos-id=<id>  "hostname"

### What did you expect to see?
command hostname to be tun on the node 

### What did you see instead?
Usage text for dcos node

**Comment by tamarrow** [comment]
fixed in #627. thanks @surdy!
