### ISSUE TITLE
use json-schema, not current config, to determine possible values for a subkey

### ISSUE THREAD

**Issue by surdy** [dcos/dcos-cli#611]
Please answer the following questions before submitting your issue. Thanks!
### What version of the DCOS CLI are you using (`dcos --version`)?

https://github.com/dcos/dcos-cli/tree/bdb6191bf7327b19c8c1d8ca2a4bbb70d038e413
### What version of DCOS are you using?

1.7 
### What operating system and version are you using?

OSX (but have been able to repro on Linux as well)
### What did you do?

If possible please provide a recipe for reproducing.
git clone https://github.com/dcos/dcos-cli
cd dcos-cli
make packages
cd cli
make env
source bin/env-setup-dev
dcos config set core.dcos_url <url>
make test
### What did you expect to see?

All the tests to succeed. I do not know if I'm doing something wrong
[test_log.txt](https://github.com/dcos/dcos-cli/files/264166/test_log.txt)
[test_log.txt](https://github.com/dcos/dcos-cli/files/264167/test_log.txt)
### What did you see instead?

```
tests/integrations/test_auth.py::test_info PASSED
tests/integrations/test_auth.py::test_version PASSED
tests/integrations/test_auth.py::test_logout_no_token PASSED
tests/integrations/test_auth.py::test_logout_with_token PASSED
tests/integrations/test_config.py::test_help PASSED
tests/integrations/test_config.py::test_info PASSED
tests/integrations/test_config.py::test_version PASSED
tests/integrations/test_config.py::test_get_existing_string_property PASSED
tests/integrations/test_config.py::test_get_existing_boolean_property PASSED
tests/integrations/test_config.py::test_get_existing_number_property PASSED
tests/integrations/test_config.py::test_get_missing_property PASSED
tests/integrations/test_config.py::test_invalid_dcos_url PASSED
tests/integrations/test_config.py::test_get_top_property FAILED
================================================================================================================================== FAILURES ==================================================================================================================================
___________________________________________________________________________________________________________________________ test_get_top_property ____________________________________________________________________________________________________________________________

env = {'DCOS_CONFIG': 'tests/data/dcos.toml', 'LANG': 'en_US.UTF-8', 'PATH': '/Users/harpreet/repos/mesosphere/dcos-cli/dcos...os/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/harpreet/dcos/dcos/bin', 'PYTHONHASHSEED': '585879583', ...}

    def test_get_top_property(env):
        stderr = (
            b"Property 'core' doesn't fully specify a value - "
            b"possible properties are:\n"
            b"core.dcos_acs_token\n"
            b"core.dcos_url\n"
            b"core.reporting\n"
            b"core.ssl_verify\n"
            b"core.timeout\n"
        )

        assert_command(['dcos', 'config', 'show', 'core'],
                       stderr=stderr,
                       returncode=1,
>                      env=env)

tests/integrations/test_config.py:91:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['dcos', 'config', 'show', 'core'], returncode = 1, stdout = '', stderr = "Property 'core' doesn't fully specify a value - possible properties are:\ncore.dcos_acs_token\ncore.dcos_url\ncore.reporting\ncore.ssl_verify\ncore.timeout\n"
env = {'DCOS_CONFIG': 'tests/data/dcos.toml', 'LANG': 'en_US.UTF-8', 'PATH': '/Users/harpreet/repos/mesosphere/dcos-cli/dcos...os/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/harpreet/dcos/dcos/bin', 'PYTHONHASHSEED': '585879583', ...}, stdin = None

    def assert_command(
            cmd,
            returncode=0,
            stdout=b'',
            stderr=b'',
            env=None,
            stdin=None):
        """Execute CLI command and assert expected behavior.

        :param cmd: Program and arguments
        :type cmd: list of str
        :param returncode: Expected return code
        :type returncode: int
        :param stdout: Expected stdout
        :type stdout: str
        :param stderr: Expected stderr
        :type stderr: str
        :param env: Environment variables
        :type env: dict of str to str
        :param stdin: File to use for stdin
        :type stdin: file
        :rtype: None
        """

        returncode_, stdout_, stderr_ = exec_command(cmd, env, stdin)

        assert returncode_ == returncode
        assert stdout_ == stdout
>       assert stderr_ == stderr
E       assert "Property 'co...ore.timeout\n" == "Property 'cor...ore.timeout\n"
E           Property 'core' doesn't fully specify a value - possible properties are:
E         + core.dcos_acs_token
E           core.dcos_url
E           core.reporting
E           core.ssl_verify
E           core.timeout

tests/integrations/common.py:83: AssertionError
---------------------------------------------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------------------------------------------
CMD: ['dcos', 'config', 'show', 'core']
STDOUT:
STDERR: Property 'core' doesn't fully specify a value - possible properties are:
core.dcos_url
core.reporting
core.ssl_verify
core.timeout
```

...

```
  py27-unit: commands succeeded
  py34-unit: commands succeeded
ERROR:   py27-integration: commands failed
ERROR:   py34-integration: commands failed
```

**Comment by jsancio** [comment]
Yes. The issue is that we are looking at the current config to determine the list of possible values. We should be looking at the `jsonschema` in `core.json`.

https://github.com/dcos/dcos-cli/blob/master/dcos/config.py#L131

`value` should be the jsonschema instead of the config file.

**Comment by tamarrow** [comment]
The reason this passes in the teamcity CI tests and not locally is because we are running the tests against config file `tests/data/dcos.toml`, and in the CI tests we append the `core.dcos_acs_token` to that file before we run the tests.

**Comment by jsancio** [comment]
Yes @tamarrow . The issue is that we should also be looking at the `core.json` jsonschema to generate the list of possible option. Maybe this is how it should work:

1. `dcos config set` look at jsonschema for possible values
1. `dcos config show` look at  jsonschema + dcos.toml for possible values
1. `dcos config unset` look at dcos.toml for possible values

What do you think?

**Comment by tamarrow** [comment]
Agreed. For `2` we should look at `dcos.toml` first, and if value is not found, than look at the json-schema for the possible values.

**Comment by larioj** [comment]
This seems to be an issue with the tests. The tests assume that they are being run on the CI, so they fail locally when nothing appends the core.dcos_acs_token value to the tests/data/dcos.toml file. Manually appending this value to the file makes the test pass but it fails later on for some other issue that I would guess is also related to running test locally vs on the CI. It is also important to mention that the tests at this current time, don't even get to the test_get_top_property. They actually fail before that at test_logout_no_token because locally tests/data/dcos.toml does not have the right permissions (should have 600). Only after you change the file permissions can you get to the test_get_top_property failure. But as stated above all that does is get you to another failure i.e. test_dcos_acs_token_env_var.

**Comment by tamarrow** [comment]
This is not an issue with the tests, but with the code itself. For `dcos config show core` for example, we show all `core` commands in the toml file, instead of all the options available as defined in the json-schema.
