### ISSUE TITLE
Support `--cli` in `dcos package list`?

### ISSUE THREAD

**Issue by nickbp** [dcos/dcos-cli#626]
Please answer the following questions before submitting your issue. Thanks!

### What version of the DCOS CLI are you using (`dcos --version`)?
git @ d2d7acf3

### What version of DCOS are you using?
Would have been 1.7, but the server is disconnected at this point.

### What operating system and version are you using?
Ubuntu 15.10

### What did you do?
If possible please provide a recipe for reproducing.

I tried to view a list of the installed CLI submodules when no longer connected to a working DC/OS cluster.
a. `dcos package list` -> URL [oldurl] is unreachable: HTTPConnectionPool... Name or service not known
b. `dcos package list --cli` -> Command not recognized

### What did you expect to see?
I would've expected `dcos package list --cli` to show a list of custom-installed local client packages from previous `dcos package install`s, without attempting to check the server.

### What did you see instead?
Command not recognized

**Comment by tamarrow** [comment]
Yes, I see `--cli` being a helpful option for `package list`. Also we can update `package list` to show `N/A` for apps and info about the clis if the cluster is unavailable.
