### ISSUE TITLE
Binary Linux CLI doesn't print the correct version

### ISSUE THREAD

**Issue by jsancio** [dcos/dcos-cli#629]
Please answer the following questions before submitting your issue. Thanks!

### What version of DCOS + DCOS CLI are you using (`dcos --version`)?
If DCOS CLI version < 0.4.5, DCOS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

```
$ ./dcos --version
dcoscli.version=SNAPSHOT
dcos.version=1.7.1
dcos.commit=0defde84e7a71ebeb5dfeca0936c75671963df48
dcos.bootstrap-id=f12bff891be7108962c7c98e530e1f2cd8d4e56b
```

### What operating system and version are you using?

```
$ uname -a
Linux localhost.localdomain 4.4.6-201.fc22.x86_64 #1 SMP Wed Mar 30 18:30:16 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### What did you do?
If possible please provide a recipe for reproducing.

```
./dcos --version
```

### What did you expect to see?
```
$ ./dcos --version
dcoscli.version=0.4.5
dcos.version=1.7.1
dcos.commit=0defde84e7a71ebeb5dfeca0936c75671963df48
dcos.bootstrap-id=f12bff891be7108962c7c98e530e1f2cd8d4e56b
```

### What did you see instead?
```
$ ./dcos --version
dcoscli.version=SNAPSHOT
dcos.version=1.7.1
dcos.commit=0defde84e7a71ebeb5dfeca0936c75671963df48
dcos.bootstrap-id=f12bff891be7108962c7c98e530e1f2cd8d4e56b
```

**Comment by tamarrow** [comment]
Fixed in teamcity config:
<img width="722" alt="screen shot 2016-06-01 at 5 12 08 pm" src="https://cloud.githubusercontent.com/assets/1292768/15729789/28198c9c-281c-11e6-9e8e-89480a9e5e08.png">
<img width="720" alt="screen shot 2016-06-01 at 5 12 02 pm" src="https://cloud.githubusercontent.com/assets/1292768/15729790/282c56ce-281c-11e6-8211-784d7fc289b6.png">

**Comment by tamarrow** [comment]
see https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcosIo_DcosCli_OsX_MacBinaryRelease and https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcosIo_DcosCli_Linux_LinuxBinaryRelease

**Comment by jsancio** [comment]
👍
