### ISSUE TITLE
feature request: assume yes for package install

### ISSUE THREAD

**Issue by laferrieren** [dcos/dcos-cli#652]
It would be nice to have a assume yes for package installs to avoid piping in yes or having to manually hit yes during the install.

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`
```
dcoscli.version=0.4.5
dcos.version=1.7-open
dcos.commit=14509fe1e7899f439527fb39867194c7a425c771
dcos.bootstrap-id=3a2b7e03c45cd615da8dfb1b103943894652cd71
```

### Current Behavior
Run `dcos package install swarm` and it asks prompts you for yes/no to continue

### Desired Behavior
Be able to run `dcos package install swarm -y` and have the package install.  

yum and apt-get offer this behavior for installing packages that allow them to be scriptable.

excerpt from `man apt-get`
       -y, --yes, --assume-yes
           Automatic yes to prompts; assume "yes" as answer to all prompts and run non-interactively. If an undesirable situation, such as changing a held package, trying to install a unauthenticated package or removing an essential package occurs then apt-get will abort. Configuration Item: APT::Get::Assume-Yes.

If I have some time this weekend I will try to sit down and open up a PR

**Comment by tamarrow** [comment]
@laferrieren we have a `--yes` flag. So you can run `dcos package install swarm --yes`

**Comment by laferrieren** [comment]
sorry, I completely missed that flag in help. :(
