### ISSUE TITLE
S3 URL results in no-op "Login successful!"

### ISSUE THREAD

**Issue by nickbp** [dcos/dcos-cli#654]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

git rev d2d7acf31432f7777936bf2d9424ee74034bfa59

### What operating system and version are you using?

Ubuntu 15.10

### What did you do?
If possible please provide a recipe for reproducing.

```
$ dcos config set core.dcos_url https://s3-us-west-2.amazonaws.com/infinity-artifacts/autodelete7d/hdfs/asdf.zip
[core.dcos_url]: changed from 'redacted' to 'https://s3-us-west-2.amazonaws.com/infinity-artifacts/autodelete7d/hdfs/asdf.zip'
$ dcos auth login
Login successful!
```

### What did you expect to see?

An error

### What did you see instead?

Instant success

**Comment by tamarrow** [comment]
Yes, if you don't have auth and you 'login' we report success if it's a valid dcos-url since for all intensive purposes you are "logged in".

**Comment by nickbp** [comment]
The example url is to a file which doesn't exist, shouldn't it throw a 404?

Other URLs produce an error, there's something with this specific host or URL format that's causing it to 'succeed'.

$ curl https://s3-us-west-2.amazonaws.com/infinity-artifacts/autodelete7d/hdfs/asdf.zip
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F0C89FC29C75AF1F</RequestId><HostId>uf4SM/FNhEc8DhFNLp7AW3/p7TwEc/bADTlLSKlRKtMqpEfGdTIYfrVzqJSEH81AL7QFP4c7mwM=</HostId></Error>

**Comment by nickbp** [comment]
WAI, the client expects 403 to mean that the user can't view the test endpoint, but that the user had successfully logged in (authed but not authorized)
