### ISSUE TITLE
dcos cli does not install on Debian 8.2, python reports 'No module named concurrent.futures' 

### ISSUE THREAD

**Issue by r0c** [dcos/dcos-cli#678]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

DCOS Version: v1.7-open

### What operating system and version are you using?
OS: Debian 8.2
Python Version: 2.7.9

### What did you do?
If possible please provide a recipe for reproducing.

Just copy and paste the one liner command shown on the dcos webpage
`mkdir -p dcos && cd dcos && 
  curl -O https://downloads.dcos.io/dcos-cli/install.sh && 
  bash ./install.sh . https://mesos01.fleetboard.dmz && 
  source ./bin/env-setup`

### What did you expect to see?
The success of the installation.

### What did you see instead?

debian-jessie:~/dcos# mkdir -p dcos && cd dcos &&    curl -O https://downloads.dcos.io/dcos-cli/install.sh &&    bash ./install.sh . http://mesos01.fleetboard.dmz &&    source ./bin/env-setup

> Installing DC/OS CLI from PyPI...
> 
> New python executable in /root/dcos/dcos/bin/python
> Installing setuptools, pip, wheel...done.
> Traceback (most recent call last):
>   File "/root/dcos/dcos/bin/dcos", line 7, in <module>
>     from dcoscli.main import main
>   File "/root/dcos/dcos/local/lib/python2.7/site-packages/dcoscli/main.py", line 7, in <module>
>     from dcos import config, constants, emitting, errors, http, subcommand, util
>   File "/root/dcos/dcos/local/lib/python2.7/site-packages/dcos/config.py", line 10, in <module>
>     from dcos import constants, jsonitem, subcommand, util
>   File "/root/dcos/dcos/local/lib/python2.7/site-packages/dcos/jsonitem.py", line 5, in <module>
>     from dcos import util
>   File "/root/dcos/dcos/local/lib/python2.7/site-packages/dcos/util.py", line 2, in <module>
>     import concurrent.futures
> ImportError: No module named concurrent.futures
> 
> debian-jessie:~/dcos/dcos# uname -a
> Linux debian-jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux
> 
> debian-jessie:~/dcos/dcos# cat /etc/debian_version
> 8.2
> 
> debian-jessie:~/dcos/dcos# pip -V
> pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by Bowbaq** [comment]
Seeing the same issue on my OSX 10.11 laptop. It seems running `$CLI_DIR/bin/pip install futures six requests prettytable` fixes it, but it's unclear why that's not just installed by default :/

Also, trying to write an ansible playbook to install the CLI, and I can't manage to get it to install those extra packages in the right spot. Using the `virtualenv` setting of the `pip` module crashes, and trying to just shell out results in ansible installing them in its own `site-packages` folder -_o_-

**Comment by jsancio** [comment]
I see. I think this is because we removed support for Python 2.7. You can try installing using Python 3 or our native bundles: https://github.com/dcos/dcos-cli/releases/tag/0.4.8
and for Linux x86-64: https://downloads.dcos.io/binaries/cli/linux/x86-64/0.4.8/dcos

**Comment by jsancio** [comment]
@r0c and @Bowbaq, we reverted that release. Install should work now. We are working on a long-term fix.

**Comment by jsancio** [comment]
@r0c and @Bowbaq, we reverted that release. Install should work now. We are working on a long-term fix.

**Comment by jsancio** [comment]
Fixed by #682. Please re-open if you still have this issue.
