### ISSUE TITLE
Syntax of dcos config show / dcos config set is inconsistent

### ISSUE THREAD

**Issue by lloesche** [dcos/dcos-cli#683]
Output of `dcos config show`
```
key=value
```

Syntax of `dcos config set`
```
key value
```

Can we either have `dcos config show` output
```
key value
```

or make `dcos config set` accept
```
key=value
```
as argument?

My often used workflow is to update the core.dcos_url value. For that I `dcos config show` the current config (because I always forget the exact param name) and then copy'paste that output as the input to `dcos config set`. It'll always throw an `Command not recognized` error because it won't accept `$ dcos config set core.dcos_url=https://dcos-cluster.url/`.

**Comment by cruhland** [comment]
Fixed by #801.
