### ISSUE TITLE
Windows Install script not activating Virtualenv

### ISSUE THREAD

**Issue by liqdfire** [dcos/dcos-cli#687]
The power shell install script is calling the bash version of activate. This is causing virtualenv to not activate, and the subsequent command for pip install dcoscli corrupts the python install.

I do not have win_bash installed, therefore the bash version would not run properly. I was following the install instructions for a user, not a developer. 

Adding the .ps1 to call the powershell version of the activate script resolved the issue.

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

CLI version 0.4.10, brand new install

### What operating system and version are you using?
Windows 10, fresh install of Python 3.4.4
I do not have win_bash as referenced in the developer setup in the github page.

### What did you do?
Ran the install.ps1 script

### What did you see instead?
The install would error out, throw "dcos" not a valid cmdlet, and corrupt my python install.

**Comment by tamar22** [comment]
Thanks for the pr! We now have binary CLIs so this install process is about to change. Test and out and let us know if you run into any problems: https://github.com/dcos/dcos-cli/releases

**Comment by tamarrow** [comment]
Thanks for the pr! We now have binary CLIs so this install process is about to change. Test and out and let us know if you run into any problems: https://github.com/dcos/dcos-cli/releases

**Comment by liqdfire** [comment]
I should be able to get to that for you early next week.

**Comment by tamarrow** [comment]
The fix is now merged!
