### ISSUE TITLE
Typing 'dcos task log' without args doesn't do anything -- print help?

### ISSUE THREAD

**Issue by nickbp** [dcos/dcos-cli#689]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

1.8-dev

### What operating system and version are you using?

Ubuntu Linux 16.04

### What did you do?
If possible please provide a recipe for reproducing.

$ dcos task log

### What did you expect to see?

An error or the contents of `dcos task log --help`. The documentation returned by `--help` shows that a task id is a required parameter.

### What did you see instead?

Empty output (right back to cmdline prompt)

**Comment by tamarrow** [comment]
This is an error with the argument parsing. See #691
