### ISSUE TITLE
dcos task shell

### ISSUE THREAD

**Issue by mgummelt** [dcos/dcos-cli#701]
Please provide a command `dcos task shell` which ssh'es into a node, and shells into the task's sandbox.  I often need to do this to poke around the e.g. docker image.  For example, in Spark, there are several relevant files in the filesystem that aren't in the sandbox, and therefore don't show up in the Mesos/DCOS UI

**Comment by tamarrow** [comment]
Can do now with `dcos task exec` thanks to @klueska
