### ISSUE TITLE
Feature request: `dcos config show all`

### ISSUE THREAD

**Issue by joel-hamill** [dcos/dcos-cli#715]
Please answer the following questions before submitting your issue. Thanks!
### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

dcoscli.version=0.4.10
### What operating system and version are you using?

MacOS
### What new feature do you want?

I would like a way to show all available CLI config options. For example, 
`$ dcos config show all`.

**Comment by tamarrow** [comment]
This should be part of #611

**Comment by ArmandGrillet** [comment]
We now have `dcos config show` doing this.
