### ISSUE TITLE
Implement update command

### ISSUE THREAD

**Issue by cruhland** [dcos/dcos-cli#736]
The `dcos --update-cli` command should replace the CLI binary if a newer version is available in Cosmos. See the [design doc](https://docs.google.com/a/mesosphere.io/document/d/1EkCG-VTmdin08aHRI-xYdjj3LZb5hiKda8DSuQiGbDI/edit?usp=sharing) for more details.

**Comment by tamarrow** [comment]
We should make sure not check for updates on `help` or `config` commands.
