### ISSUE TITLE
dcos cluster resize command not found

### ISSUE THREAD

**Issue by viveksatasiya** [dcos/dcos-cli#745]
Hello,

I am using DC/OS 1.7-open version and dcos-cli 0.4.10 version.
I have installed DC/OS on AWS.

I have seen introductory video from this link . [https://www.youtube.com/watch?v=0I6qG9RQUnY](url)

In that video, he run `dcos cluster resize 100` which command creates new 100 EC2 instances on AWS.

But I cannot find similar command on my cli.
Is there any mistake I am doing?

Thanks.

**Comment by tamarrow** [comment]
This was a product demo only- that feature doesn't exist. Apologies for the confusion.
