### ISSUE TITLE
Improve reporting of 403 errors from Cosmos

### ISSUE THREAD

**Issue by cruhland** [dcos/dcos-cli#763]
The current message can be misleading. If a repo is added to Cosmos' repo list that responds with a 403 status when Cosmos attempts to retrieve it, then when a request like `/package/describe` is made to Cosmos, it will respond with the following (for example):

```json
{
    "data": {
        "method": "GET",
        "status": 403,
        "uri": "https://downloads.mesosphere.com/spark/assets/stub-universe-spark.zip"
    },
    "message": "Unexpected down stream http error: GET https://downloads.mesosphere.com/spark/assets/stub-universe-spark.zip 403",
    "type": "GenericHttpError"
}
```

This gets reported by the CLI as:

```
You are not authorized to perform this operation
```

It would help with debugging if the CLI could at least show the `message` field of the JSON response from Cosmos.

**Comment by cruhland** [comment]
We might also consider changing how Cosmos reports a 403 status from a repo URL.

**Comment by tamarrow** [comment]
The full cosmos error is printed in `--debug` mode. The actual fix should be made in cosmos. Created: https://mesosphere.atlassian.net/browse/DCOS-10456
