### ISSUE TITLE
CLI prompts for "authentication token", should be "OpenID Connect ID token"

### ISSUE THREAD

**Issue by emanic** [dcos/dcos-cli#775]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

0.4.12

### What operating system and version are you using?

Mac OSX Yosemite

### What did you do?

I followed the instructions in the open-source documentation https://dcos.io/docs/1.8/administration/id-and-access-mgt/managing-authentication/  and received a prompt to enter my "authentication token"

### What did you expect to see?

A prompt to enter my "OpenID Connect ID token"

### What did you see instead?

As noted in "What did you do" :)

CC: @alberts @jgehrcke

**Comment by tamarrow** [comment]
@emanic the cli only supports oauth authentication for open clusters right now (we have an open jira to expand this). What prompt did you see? 

The docs are correct, you should have seen 

```Please go to the following link in your browser:

    https://<public-master-ip>/login?redirect_uri=urn:ietf:wg:oauth:2.0:oob

Enter authentication token:
```

**Comment by emanic** [comment]
@tamarrow Thanks so much. You are correct, the documentation matches what is in the prompt right now. However, it turns out that the prompt has the wrong term. Actually, there are two tokens and we need to differentiate them clearly as it is causing a lot of confusion in the field. The token that the CLI is requesting here is actually the "OpenID Connect ID token", not the DC/OS "authentication token." Let me know if you would like to discuss this further on Monday. :))) I know it is confusing.

**Comment by tamarrow** [comment]
@alberts you okay with changing the cli prompt to "OpenID Connect ID token"?

**Comment by alberts** [comment]
I'm okay with this. Let's see if @jgehrcke agrees and we can proceed.

**Comment by jgehrcke** [comment]
Yes, sure, that's what it is :)

In the spec it is called `ID Token` (note the capitalization, but that's not too important).

For reference: http://openid.net/specs/openid-connect-core-1_0.html#IDToken

> The primary extension that OpenID Connect makes to OAuth 2.0 to enable End-Users to be Authenticated is the ID Token data structure. The ID Token is a security token that contains Claims about the Authentication of an End-User  [...]
