### ISSUE TITLE
Automatically ask to install CLI tools if applicable and package already installed

### ISSUE THREAD

**Issue by lloesche** [dcos/dcos-cli#805]
I have a cluster running cassandra but my dcos-cli doesn't have the cassandra subcommand.

Instead of relying on users knowing about the `--cli` arg (which by the way has a very non descriptive `Command line only.` help text) it would be nice if dcos-cli recognises that I have cassandra already installed but am missing the appropriate subcommand and just offered to install it locally.

**Comment by ArmandGrillet** [comment]
Those are valid points, closing the issue as it duplicates #961 which has more comments.
