### ISSUE TITLE
"dcos" library on pypi is unable to be resolved during build

### ISSUE THREAD

**Issue by huntc** [dcos/dcos-cli#819]
This is a general question about how the dcos python is published to pypi. 

[Our CI build is failing](https://travis-ci.org/typesafehub/conductr-cli/builds/170710476) with:

```
Reading https://pypi.python.org/simple/dcos/
No local packages or download links found for dcos<0.5.0,>=0.4.14
error: Could not find suitable distribution for Requirement.parse('dcos<0.5.0,>=0.4.14')
```

I overcame this issue locally via:

```
pip3 install -e .
```

I'm thinking that our `python setup.py test` should be all that is required (Python3).

It seems strange that [all of the other packages we have ](https://github.com/huntc/conductr-cli/blob/74b1ef4cbb28c16503162e9701cca163783a63df/setup.py#L10-L16) are able to be located just fine.

**Comment by tamarrow** [comment]
This is because `python setup.py test` doesn't install wheels, but `.tar.gz` files. We only publish wheels, which is supported by `pip`, which is why the `pip` command succeeded.

**Comment by huntc** [comment]
Is there a reason to not publish tgz files? This appears to be common practice.

**Comment by huntc** [comment]
Ok we will do that. Python is surprisingly complex in this regard!

Thanks.
