### ISSUE TITLE
Provide a non-interactive login option for the auth command

### ISSUE THREAD

**Issue by willgorman** [dcos/dcos-cli#825]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

0.4.14

### What operating system and version are you using?

RHEL 7.2

### What did you do?
If possible please provide a recipe for reproducing.

`echo 'username\npassword\n' | dcos auth login`

### What did you expect to see?

`Login successful!`

### What did you see instead?

`username@172.17.0.2's password:`

---

I'm working on using dcos-docker to run integration tests and the easiest way to do some of the setup appears to be with the dcos-cli but it's hard to authenticate without manual input.  I understand the rational for not taking the password from redirected input but it'd be nice to be able to provide it through configuration or the environment.

**Comment by willgorman** [comment]
I guess this isn't really needed.  As a workaround it's possible to just bypass `dcos auth login` by grabbing a token via curl and setting it to `core.dcos_acs_token`

```
curl -H "Accept: application/json" \
     -H "Content-type: application/json" \
     -X POST -d '{"uid":"username","password":"password"}' \
     http://172.17.0.2/acs/api/v1/auth/login \
     | jq ".token" | xargs dcos config set core.dcos_acs_token
```

**Comment by tamarrow** [comment]
Yes, but we're also adding some flags to make this possible through the cli :)
