### ISSUE TITLE
Master.slave_base_url() from mesos.py implemented incorrectly

### ISSUE THREAD

**Issue by klueska** [dcos/dcos-cli#827]
The `slave_base_url()` function linked below is implemented incorrectly:

https://github.com/dcos/dcos-cli/blob/master/dcos/mesos.py#L318

It accesses member variable that do not exist in the master (only in the DCOS client).
It should probably just be removed.

**Comment by tamarrow** [comment]
Looks like its never used, so we can just remove it.
