### ISSUE TITLE
dcos cli login for CI

### ISSUE THREAD

**Issue by andreimc** [dcos/dcos-cli#845]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
If DC/OS CLI version < 0.4.5, DC/OS version can be found at `http://dcos_url/dcos-metada/dcos-version.json`

dcoscli.version=0.4.14
dcos.version=1.8.6
dcos.commit=cfccfbf84bbba30e695ae4887b65db44ff216b1d
dcos.bootstrap-id=405172d16eaff8798d6b090dac99b51a8a9004d7

### What operating system and version are you using?

debian/amd64

My problem is that we use our CI to perform deployments and the DCOS token from oAuth expires after 5 days.

How can we login from a non-interactive environment ? With oauth ?

**Comment by justinclayton** [comment]
Looks like the code (for the CLI anyways) doesn't currently support anything other than username/password pair: https://github.com/dcos/dcos-cli/blob/3b3eff70cae37c5f47a78ece64c8aa80742e2904/dcos/http.py#L343-L361

However, you can use the auth API directly: https://dcos.io/docs/1.8/administration/id-and-access-mgt/auth-api/

**Comment by richardgirges** [comment]
We're using open-source DC/OS and this issue has become a problem for us as well. We're trying to use our CI servers to perform deployments to DC/OS but there doesn't appear to be any documented way to create a non-expiring API token (or at least a token with a longer TTL) in open-source DC/OS. 

Been pulling my hair out trying to figure out a work around for this.  We currently have to manually log into DC/OS with the dcos-cli to generate a refreshed API token every five days to keep our CI from breaking. We may be switching to vanilla Marathon if we can't figure out a workaround soon, but any input on this issue would be appreciated.

**Comment by richardgirges** [comment]
I've come up with a straight-up hack for creating an authentication token for use with external applications (such as Jenkins) in open-source DC/OS. This approach bypasses the OAuth flow and can allow for generating a longer lasting expiration date...

Blog article with instructions here:
https://medium.com/@richardgirges/authenticating-open-source-dc-os-with-third-party-services-125fa33a5add#.10p755s0p

**Comment by tamarrow** [comment]
Great blog post! Yes, unfortunately there's no good way to script oauth login (because it needs interactive with the browser). You can now script login with enterprise builds. We will be adding more authentication methods to open DC/OS in the future which will allow easy scripting.

**Comment by pkazi** [comment]
There us open source utiity to create oauth token using GITHUB as oauth provider for open source dcos.
Below blog explains it better, it helped me lot in our auto deployments.
http://blog.originate.com/blog/2017/04/27/continuous-delivery-to-dcos-from-circleci/
