### ISSUE TITLE
dcos node --help advertises deprecated options.

### ISSUE THREAD

**Issue by nfnt** [dcos/dcos-cli#865]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
This is while testing DC/OS 1.9.
```
$ dcos --version
dcoscli.version=0.4.14
dcos.version=1.9-dev
dcos.commit=a713519364e609979618e9fd51a164d53b5ad298
dcos.bootstrap-id=59a23ddf6042daef57c5773524ddae6d8ec0bb3e
```

### What operating system and version are you using?
macOS Sierra

### What did you do?
`dcos node --help` to figure out how to `ssh` into a node.

### What did you expect to see?
That it documents `--mesos-id` in the "Options:" section as the current way to describe an agent node.

### What did you see instead?
`--slave=<agent-id>` as the option to describe an agent node, which is deprecated. `--mesos-id` isn't even part of the "Options" subsection. It is documented in "Usage" though.

**Comment by tamarrow** [comment]
#966
