### ISSUE TITLE
`dcos service log` uses the wrong user name and the private, not public, ip address

### ISSUE THREAD

**Issue by deanwampler** [dcos/dcos-cli#869]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
```
$ dcos --version
dcoscli.version=0.4.14
dcos.version=1.8.7
dcos.commit=1b43ff7a0b9124db9439299b789f2e2dc3cc086c
dcos.bootstrap-id=e73ba2b1cd17795e4dcb3d6647d11a29b9c35084
```

### What operating system and version are you using?

Ubuntu 16.04.1 in the cluster, macOS Sierra locally, where the CLI is executed.

### What did you do?
Simple: Ran the following from my Mac:
```
$ dcos service log marathon
Running `ssh core@10.10.1.168 journalctl -n 10 -u dcos-marathon`
(eventually times out)
```

The other `dcos service` commands and even `dcos task log ...` commands don't have this issue.

### What did you expect to see?

While it appears you are assuming CoreOS, which is a bad assumption to make to begin with, it's still possible I might want to use another user name. Also, for Ubuntu, etc. it's common to use `ubuntu`. At the very least, I should be able to configure the user name somewhere, like `$HOME/.dcos/dcos.toml` (if no where else suitable...). And it should never use the private IP address and never assume I'm running the CLI within the cluster.

### What did you see instead?

See above.

**Comment by tamarrow** [comment]
Thanks for the report. With the latest CLI release (0.4.15) `dcos service log marathon` uses the public IP. We default the user to `core` but you can override this by providing a SSH config file (`--ssh-config-file=/path/tof/file`). Hope that helps!

**Comment by deanwampler** [comment]
Thanks, that should do it. I believe this affects `dcos node` and perhaps a few other commands, too, in case they are implemented different.

I'll close this now.
