### ISSUE TITLE
If not authed already, the commands should not prompt for the auth token.

### ISSUE THREAD

**Issue by deanwampler** [dcos/dcos-cli#871]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?
```
dcoscli.version=0.4.14
dcos.version=1.8.7
dcos.commit=1b43ff7a0b9124db9439299b789f2e2dc3cc086c
dcos.bootstrap-id=e73ba2b1cd17795e4dcb3d6647d11a29b9c35084
```

### What operating system and version are you using?
Running the CLI on macOS Sierra, Ubuntu in the cluster.

### What did you do?
If possible please provide a recipe for reproducing.
Say you haven't authenticated the CLI yet and you run `dcos node` (for example). It prompts you to enter the connect ID. While "convenient" for interactive use, it causes lots of problems in automation scripts. It's fine to print the message about what to do, but it should exit with status != 0, not prompt for unplanned input.

To give you a sketch of what I have to do at the moment, suppose I want to run several dcos commands in a `bash` automation script. I've put code like the following around the first command in each script (where `error` will print an error message and then exit...):

```
echo "" | dcos node  || error "Please run 'dcos auth login', then try again"

### What did you expect to see?

The error message you currently see with instructions, but it exits with status 1 instead of prompting for the token.

### What did you see instead?

See above.

**Comment by tamarrow** [comment]
If you don't have an auth token set,  none of the commands will work :) Why don't you authenticate at the top of your script? If the token is invalid, the command will error with `Your core.dcos_acs_token is invalid. Please run: `dcos auth login`` and exit with a returncode of 1 (no interaction).

**Comment by deanwampler** [comment]
That's not always possible. Some of our scripts are run optionally by the user after the installation and if they haven't done this step, then buried invocations of `dcos` commands cause problems with the current behavior. We can certainly do the hack I described in every script at the top, but wouldn't make sense to provide a way to test this situation in a more natural way?
