### ISSUE TITLE
Question about mesos DC/OS endpoint

### ISSUE THREAD

**Issue by enlinxu** [dcos/dcos-cli#873]
I am wondering where can I find the Mesos rest api endpoint documentation. In my on prem Mesos 0.28 + Marathon version, I can get the statistics from endpoint http://agent.com:5051/monitor/statistics.json
But in my aws dc/os installation, I couldn't get the statistics. Actually, all the endpoints are different in DC/OS and on prem mesos. In my dc/os , the url is http://masterIP/mesos/state, in on prem mesos, it's http://master:5050/state

Where can I get the docs?

From Mesos 
What version of DC/OS + DC/OS CLI are you using (dcos --version)?

Enlins-MacBook-Pro:dcos Enlin$ dcos --version
dcoscli.version=0.4.10
dcos.version=1.8.4
dcos.commit=e64024af95b62c632c90b9063ed06296fcf38ea5
dcos.bootstrap-id=5b4aa43610c57ee1d60b4aa0751a1fb75824c083

What operating system and version are you using?

I am using DC/OS cloudformation

What did you do?

Running Rest api.

What did you expect to see?

I want to use rest api to get running task consumption information.

**Comment by tamarrow** [comment]
The docs are here: https://docs.mesosphere.com/

Monitoring info is here: https://docs.mesosphere.com/1.8/usage/managing-services/list/

**Comment by enlinxu** [comment]
Thanks @tamarrow . I still don't see rest api endpoint. Basically I am looking for the equivalent (or similar) to http://mesos.apache.org/documentation/latest/endpoints/

**Comment by tamarrow** [comment]
You can see the configured endpoints at `/mesos/help`

DC/OS itself has APIs that you might also find helpful for getting task information
