### ISSUE TITLE
Update the development dependencies in the README

### ISSUE THREAD

**Issue by klueska** [dcos/dcos-cli#883]
Development now depends on python 3.5 instead of 3.4.

Also, the python development libraries are now required to build the `cryptography` package, so these should be listed too.

**Comment by tamarrow** [comment]
#878 fixes the version in the README

**Comment by tamarrow** [comment]
`cryptography` isn't a development dependency, It's part of the cli setup. Those requirements are external requirements from the cli needed only if you are developing. The wording is a bit confusing.
