### ISSUE TITLE
Python 3.6 installed but 3.5 is required

### ISSUE THREAD

**Issue by szwed** [dcos/dcos-cli#895]
Please answer the following questions before submitting your issue. Thanks!

### What version of DC/OS + DC/OS CLI are you using (`dcos --version`)?

master branch:
`git clone https://github.com/dcos/dcos-cli`

### What operating system and version are you using?

macOS Sierra:
```
sw_vers -productVersion
10.12.2
```
### What did you do?

```
git clone https://github.com/dcos/dcos-cli
cd dcos-cli
make env
bin/env.sh
Cannot find supported python version 3.5. Exiting...
make: *** [env] Error 1
```

### What did you expect to see?

Compiled dcos-cli binaries.

### What did you see instead?

Error message.

**Comment by tamarrow** [comment]
You are downloading from source. We target python 3.5, so want to make sure developers use the same version. 

Binaries for all versions are listed here: https://github.com/dcos/dcos-cli/releases
