### ISSUE TITLE
Slack channel?

### ISSUE THREAD

**Issue by msabramo** [dcos/dcos-cli#949]
Just wondering if there's a Slack channel where we can interact with the developers?

Sometimes when working on PRs, there are issues that can probably be hashed out quickly by having a quick chat in Slack rather than going back and forth on comments in the PRs.

**Comment by tamarrow** [comment]
There is! You can join https://dcos-community.slack.com/

**Comment by msabramo** [comment]
![screen shot 2017-03-22 at 3 49 06 pm](https://cloud.githubusercontent.com/assets/305268/24224208/245183ac-0f17-11e7-95ac-fd51ab399e76.png)

**Comment by tamarrow** [comment]
You can create an account here: http://chat.mesosphere.com/

**Comment by msabramo** [comment]
OK, I'm in. Is there a channel for dcos-cli?

**Comment by tamarrow** [comment]
I've asked to add one, in the meantime you can dm at tamar-mesosphere

**Comment by tamarrow** [comment]
channel has been added!

**Comment by msabramo** [comment]
Cool. I'll close this then.
