### ISSUE TITLE
Suggest installing subcommand if there is one and user doesn't have it installed

### ISSUE THREAD

**Issue by msabramo** [dcos/dcos-cli#961]
like https://launchpad.net/command-not-found does on Ubuntu.

So right now we have:

```
$ dcos spark
'spark' is not a dcos command.
```

It would be cool if we had instead:

```
$ dcos spark
'spark' is not a dcos command.
The command 'spark' can be found in the following DC/OS packages:
   * spark
  Try: dcos package install --cli <selected package>
```

**Comment by tamarrow** [comment]
Great suggestion. Sadly, this won't work for all subcommands because the command name isn't necessarily the package name. For example installing dcos-enterprise-cli package results in the security subcommand. But something is better than nothing.

**Comment by ArmandGrillet** [comment]
We've slightly improved the error message:
```
➜  ~ dcos yolo
Error: unknown command "yolo" for "dcos"
Run 'dcos --help' for usage.
```
@bamarni We've seen a ticket about that recently in our backlog, do you think we'll ever be able to improve the error message?
