### ISSUE TITLE
bash/zsh completions

### ISSUE THREAD

**Issue by msabramo** [dcos/dcos-cli#962]
It would be nice to have bash and/or zsh completion. 

See also: https://github.com/stuartleeks/bash-dcos

**Comment by ArmandGrillet** [comment]
This will be available in the coming days, both for bash and zsh. Keeping this issue open in the meantime.

**Comment by rgo3** [comment]
This is available and documented in the DC/OS [docs](https://docs.mesosphere.com/1.12/cli/autocompletion/)
